/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di.uniba.map.b.lab.swing.esercizi;

import di.uniba.map.b.lab.collection.esercizi.Articolo;
import di.uniba.map.b.lab.collection.esercizi.Utente;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pierpaolo
 */
public class NegozioSwing extends javax.swing.JFrame {

    /**
     * Creates new form NegozioSwing
     */
    public NegozioSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuDB = new javax.swing.JMenu();
        menuItemConnetti = new javax.swing.JMenuItem();
        menuItemDisconnetti = new javax.swing.JMenuItem();
        menuInsert = new javax.swing.JMenu();
        menuItemArticolo = new javax.swing.JMenuItem();
        menuItemUtente = new javax.swing.JMenuItem();
        menuSearch = new javax.swing.JMenu();
        menuItemCercaArticolo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Amazon dei poveri");

        menuDB.setText("Database");

        menuItemConnetti.setText("Connetti");
        menuItemConnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConnettiActionPerformed(evt);
            }
        });
        menuDB.add(menuItemConnetti);

        menuItemDisconnetti.setText("Disconnetti");
        menuItemDisconnetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDisconnettiActionPerformed(evt);
            }
        });
        menuDB.add(menuItemDisconnetti);

        jMenuBar1.add(menuDB);

        menuInsert.setText("Inserimento");
        menuInsert.setEnabled(false);

        menuItemArticolo.setText("Articolo...");
        menuItemArticolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArticoloActionPerformed(evt);
            }
        });
        menuInsert.add(menuItemArticolo);

        menuItemUtente.setText("Utente...");
        menuItemUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUtenteActionPerformed(evt);
            }
        });
        menuInsert.add(menuItemUtente);

        jMenuBar1.add(menuInsert);

        menuSearch.setText("Search");
        menuSearch.setEnabled(false);

        menuItemCercaArticolo.setText("Cerca articolo...");
        menuItemCercaArticolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCercaArticoloActionPerformed(evt);
            }
        });
        menuSearch.add(menuItemCercaArticolo);

        jMenuBar1.add(menuSearch);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemArticoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArticoloActionPerformed
        // TODO add your handling code here:
        DialogArticolo dga = new DialogArticolo(this, true);
        dga.setVisible(true);
        Articolo articolo = dga.getArticolo();
        if (articolo != null) {
            try {
                DBNegozio.getInstance().insertArticolo(articolo);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuItemArticoloActionPerformed

    private void menuItemUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUtenteActionPerformed
        // TODO add your handling code here:
        DialogUtente dgu = new DialogUtente(this, true);
        dgu.setVisible(true);
        Utente utente = dgu.getUtente();
        if (utente != null) {
            try {
                DBNegozio.getInstance().insertUser(utente);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_menuItemUtenteActionPerformed

    private void menuItemConnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConnettiActionPerformed
        // TODO add your handling code here:
        try {
            DBNegozio.getInstance().connect();
            menuInsert.setEnabled(true);
            menuSearch.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage(), "Connection Error", JOptionPane.ERROR_MESSAGE);
            menuInsert.setEnabled(false);
            menuSearch.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemConnettiActionPerformed

    private void menuItemDisconnettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDisconnettiActionPerformed
        // TODO add your handling code here:
        try {
            DBNegozio.getInstance().disconnect();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            menuInsert.setEnabled(false);
            menuSearch.setEnabled(false);
        }
    }//GEN-LAST:event_menuItemDisconnettiActionPerformed

    private void menuItemCercaArticoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCercaArticoloActionPerformed
        // TODO add your handling code here:
        DialogRicerca dgr = new DialogRicerca(this, true);
        dgr.setVisible(true);
    }//GEN-LAST:event_menuItemCercaArticoloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NegozioSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NegozioSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NegozioSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NegozioSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NegozioSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuDB;
    private javax.swing.JMenu menuInsert;
    private javax.swing.JMenuItem menuItemArticolo;
    private javax.swing.JMenuItem menuItemCercaArticolo;
    private javax.swing.JMenuItem menuItemConnetti;
    private javax.swing.JMenuItem menuItemDisconnetti;
    private javax.swing.JMenuItem menuItemUtente;
    private javax.swing.JMenu menuSearch;
    // End of variables declaration//GEN-END:variables
}
